// The terms of use (#62). Short on purpose: a free, non-commercial playground
// owes its visitors a no-warranty statement, an honest description of what a
// model's output is, the pointer to each model's own licence, and a line on
// misuse. Australian Consumer Law guarantees cannot be excluded, so the
// liability clause says so rather than pretending otherwise.

import { createLazyFileRoute, Link } from "@tanstack/react-router";

import { ContactLink, ExternalLink, LegalPage, Section } from "@/components/legal/LegalPage";
import { JURISDICTION, OPERATOR, SITE_ORIGIN, SOURCE_URL } from "@/legal/site";

export const Route = createLazyFileRoute("/terms")({
  component: TermsPage,
});

/** The AI-output statement, word for word — the generative pages repeat it. */
export const AI_OUTPUT_TERMS =
  "Model outputs are generated by machine-learning models, not written or checked by a person. They can be wrong, biased or offensive, and they are not professional advice.";

function TermsPage() {
  return (
    <LegalPage
      title="Terms of use"
      intro={
        <p>
          These terms cover your use of {SITE_ORIGIN.replace("https://", "")}, a free,
          non-commercial playground run by {OPERATOR}. By using the site you agree to them. If
          you do not, please do not use it.
        </p>
      }
    >
      <Section id="service" title="The service">
        <p>
          The site lets you download open machine-learning models and run them in your own
          browser, on your own hardware. It is provided free, as an experiment and a teaching
          tool. It may change, break or be withdrawn at any time without notice.
        </p>
      </Section>

      <Section id="outputs" title="Model outputs">
        <p data-testid="terms-ai-output">{AI_OUTPUT_TERMS}</p>
        <p>
          Do not rely on an output for a medical, legal, financial, safety or other decision that
          matters. Synthetic speech, generated text and edited images are machine-made. Do not
          present them as something a real person said, wrote or did.
        </p>
      </Section>

      <Section id="inputs" title="Your inputs">
        <p>
          What you give a model stays on your device (see{" "}
          <Link to="/privacy" className="underline underline-offset-2">privacy</Link>). You are
          responsible for having the right to use it: a photo of someone, a recording, a document
          or a dataset.
        </p>
      </Section>

      <Section id="licences" title="Model and dataset licences">
        <p>
          Every model and dataset belongs to its publisher and comes under its own licence. Most
          are permissive. Some are for non-commercial use only, one has its publisher&apos;s own
          terms, and a few state no licence at all. Each model picker shows the licence before
          you load anything, and the{" "}
          <Link to="/licences" className="underline underline-offset-2">licences page</Link> lists
          them all. Following a model&apos;s licence when you use what it produced is up to you.
        </p>
      </Section>

      <Section id="use" title="Acceptable use">
        <p>Do not use the site to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>break the law or infringe anyone&apos;s rights;</li>
          <li>
            impersonate a real person, or make synthetic media of someone without their
            consent;
          </li>
          <li>harass, deceive or harm anyone;</li>
          <li>
            interfere with the site, or with the services it relies on (for example, by
            scripting bulk downloads).
          </li>
        </ul>
      </Section>

      <Section id="liability" title="No warranty, limited liability">
        <p>
          The site is provided &ldquo;as is&rdquo;, without warranties of any kind. To the extent
          the law allows, {OPERATOR} is not liable for any loss arising from your use of the site
          or of any output, including lost data and any effect of running a model on your
          device&apos;s performance, battery or storage.
        </p>
        <p>
          Nothing in these terms excludes, restricts or modifies any right or remedy you have
          under the Australian Consumer Law, or under other law, that cannot lawfully be
          excluded.
        </p>
      </Section>

      <Section id="code" title="The code">
        <p>
          The site&apos;s own source code is open source under the MIT licence, at{" "}
          <ExternalLink href={SOURCE_URL}>{SOURCE_URL.replace("https://", "")}</ExternalLink>. The
          open-source packages it is built on are listed on the{" "}
          <Link to="/licences" className="underline underline-offset-2">licences page</Link>.
        </p>
      </Section>

      <Section id="law" title="Governing law and contact">
        <p>
          These terms are governed by the laws in force in {JURISDICTION}. They may be updated;
          the date at the top says when they last changed. Questions go to <ContactLink />.
        </p>
      </Section>
    </LegalPage>
  );
}
