import { describe, expect, it } from "vitest";

import fixture from "./fixtures/cartpole-trajectory.json";
import {
  CartPole,
  cartPoleDynamics,
  type CartPoleState,
  THETA_THRESHOLD,
  TIME_LIMIT,
  X_THRESHOLD,
} from "./cartPole";

describe("CartPole — pinned to Gymnasium's own trajectory", () => {
  it("matches the committed Gymnasium trajectory step for step", () => {
    // Generated by Gymnasium (scripts/make-cartpole-fixture.py), not by us.
    // Assert the physics, never only the learning: an env with a sign error
    // still trains.
    const env = new CartPole();
    env.resetTo(fixture.initial as CartPoleState);
    for (const [i, step] of fixture.steps.entries()) {
      const r = env.step(step.action);
      for (let k = 0; k < 4; k++) {
        expect(env.state[k], `step ${i}, component ${k}`).toBeCloseTo(step.state[k], 12);
      }
      expect(r.reward).toBe(step.reward);
      expect(r.terminated).toBe(step.terminated);
    }
    expect(fixture.steps[fixture.steps.length - 1].terminated).toBe(true);
    expect(fixture.source).toMatch(/gymnasium/);
  });

  it("terminates just past 12 degrees and just past 2.4 m, and not before", () => {
    const at = (s: CartPoleState) => {
      const env = new CartPole();
      env.resetTo(s);
      return env.step(1).terminated;
    };
    // Zero velocities, so one step moves nothing but the velocities.
    expect(at([0, 0, THETA_THRESHOLD - 1e-6, 0])).toBe(false);
    expect(at([0, 0, THETA_THRESHOLD + 1e-6, 0])).toBe(true);
    expect(at([X_THRESHOLD - 1e-6, 0, 0, 0])).toBe(false);
    expect(at([-(X_THRESHOLD + 1e-6), 0, 0, 0])).toBe(true);
  });

  it("falls the way it leans with zero net force", () => {
    // Gravity alone must win in the direction of the lean. A sign error in
    // thetaacc makes the pole stand itself back up.
    for (const lean of [0.05, -0.05]) {
      let s: CartPoleState = [0, 0, lean, 0];
      for (let i = 0; i < 20; i++) s = cartPoleDynamics(s, 0, 0);
      expect(Math.sign(s[2])).toBe(Math.sign(lean));
      expect(Math.abs(s[2])).toBeGreaterThan(Math.abs(lean));
    }
  });

  it("truncates at 500 steps, which is not a termination", () => {
    const env = new CartPole(3);
    env.resetTo([0, 0, 0, 0]);
    env.step(1);
    env.step(0);
    expect(env.step(1)).toMatchObject({ terminated: false, truncated: true });
    expect(TIME_LIMIT).toBe(500);
  });

  it("pays 1 per step, including the one on which it falls", () => {
    const env = new CartPole();
    env.resetTo([0, 0, THETA_THRESHOLD, 0.5]);
    expect(env.step(1)).toMatchObject({ reward: 1, terminated: true });
    expect(() => env.step(1)).toThrow(/finished episode/);
  });

  it("gives the same initial state for the same seed, drawn from ±0.05", () => {
    const a = new CartPole().reset(4);
    const b = new CartPole().reset(4);
    expect(Array.from(a)).toEqual(Array.from(b));
    expect(Array.from(new CartPole().reset(5))).not.toEqual(Array.from(a));
    for (const v of a) expect(Math.abs(v)).toBeLessThanOrEqual(0.05);
  });
});
