# Generated by Django 5.1.3 on 2026-07-02 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('task', models.CharField(choices=[('llm', 'Language model'), ('vision', 'Computer vision'), ('embedding', 'Embedding'), ('audio', 'Audio'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('weights_url', models.URLField(blank=True, max_length=500)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InferenceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inference_runs', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='registry.modelcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='modelcard',
            index=models.Index(fields=['task'], name='registry_mo_task_dc239c_idx'),
        ),
        migrations.AddIndex(
            model_name='modelcard',
            index=models.Index(fields=['is_public'], name='registry_mo_is_publ_1bdbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['-created_at'], name='registry_in_created_dc0cf7_idx'),
        ),
    ]
