"""Regenerate src/rl/envs/fixtures/cartpole-trajectory.json from Gymnasium itself.

The fixture pins `cartPole.ts` against the upstream implementation rather than
against our own expectations: a sign error in the pole update trains perfectly
happily, so only an outside reference can catch it.

    uv venv /tmp/gym && uv pip install --python /tmp/gym/bin/python gymnasium numpy
    /tmp/gym/bin/python scripts/make-cartpole-fixture.py > src/rl/envs/fixtures/cartpole-trajectory.json
"""

import json

import gymnasium as gym
import numpy as np

env = gym.make("CartPole-v1")
env.reset(seed=0)
u = env.unwrapped
init = [0.01, -0.02, 0.03, 0.04]
u.state = np.array(init, dtype=np.float64)
u.steps_beyond_terminated = None
# A fixed, deliberately uneven pattern so both force directions and both lean
# directions occur, then a constant push until the pole falls.
pattern = [1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1]
steps = []
for i in range(200):
    a = pattern[i % len(pattern)] if i < 60 else 1
    obs, r, term, trunc, _ = env.step(a)
    steps.append(
        {"action": a, "state": [float(v) for v in u.state], "reward": float(r), "terminated": bool(term)}
    )
    if term:
        break
print(
    json.dumps(
        {
            "source": f"gymnasium {gym.__version__} CartPole-v1, env.unwrapped.state set directly, generated by scripts/make-cartpole-fixture.py",
            "initial": init,
            "steps": steps,
        },
        indent=1,
    )
)
