/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeroShotObjectDetectionRouteImport } from './routes/zero-shot-object-detection'
import { Route as ZeroShotImageClassificationRouteImport } from './routes/zero-shot-image-classification'
import { Route as VideoClassificationRouteImport } from './routes/video-classification'
import { Route as VadRouteImport } from './routes/vad'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TextToSpeechRouteImport } from './routes/text-to-speech'
import { Route as TextToAudioRouteImport } from './routes/text-to-audio'
import { Route as TensorRouteImport } from './routes/tensor'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SegmentationRouteImport } from './routes/segmentation'
import { Route as PoseRouteImport } from './routes/pose'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ObjectDetectionRouteImport } from './routes/object-detection'
import { Route as MaskGenerationRouteImport } from './routes/mask-generation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImageToTextRouteImport } from './routes/image-to-text'
import { Route as ImageFeaturesRouteImport } from './routes/image-features'
import { Route as ImageClassificationRouteImport } from './routes/image-classification'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DepthRouteImport } from './routes/depth'
import { Route as AudioToAudioRouteImport } from './routes/audio-to-audio'
import { Route as AudioClassificationRouteImport } from './routes/audio-classification'
import { Route as AsrRouteImport } from './routes/asr'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksSlugRouteImport } from './routes/tasks.$slug'

const ZeroShotObjectDetectionRoute = ZeroShotObjectDetectionRouteImport.update({
  id: '/zero-shot-object-detection',
  path: '/zero-shot-object-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeroShotImageClassificationRoute =
  ZeroShotImageClassificationRouteImport.update({
    id: '/zero-shot-image-classification',
    path: '/zero-shot-image-classification',
    getParentRoute: () => rootRouteImport,
  } as any)
const VideoClassificationRoute = VideoClassificationRouteImport.update({
  id: '/video-classification',
  path: '/video-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const VadRoute = VadRouteImport.update({
  id: '/vad',
  path: '/vad',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToSpeechRoute = TextToSpeechRouteImport.update({
  id: '/text-to-speech',
  path: '/text-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToAudioRoute = TextToAudioRouteImport.update({
  id: '/text-to-audio',
  path: '/text-to-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const TensorRoute = TensorRouteImport.update({
  id: '/tensor',
  path: '/tensor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentationRoute = SegmentationRouteImport.update({
  id: '/segmentation',
  path: '/segmentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PoseRoute = PoseRouteImport.update({
  id: '/pose',
  path: '/pose',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectDetectionRoute = ObjectDetectionRouteImport.update({
  id: '/object-detection',
  path: '/object-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const MaskGenerationRoute = MaskGenerationRouteImport.update({
  id: '/mask-generation',
  path: '/mask-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToTextRoute = ImageToTextRouteImport.update({
  id: '/image-to-text',
  path: '/image-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageFeaturesRoute = ImageFeaturesRouteImport.update({
  id: '/image-features',
  path: '/image-features',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageClassificationRoute = ImageClassificationRouteImport.update({
  id: '/image-classification',
  path: '/image-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DepthRoute = DepthRouteImport.update({
  id: '/depth',
  path: '/depth',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioToAudioRoute = AudioToAudioRouteImport.update({
  id: '/audio-to-audio',
  path: '/audio-to-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioClassificationRoute = AudioClassificationRouteImport.update({
  id: '/audio-classification',
  path: '/audio-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const AsrRoute = AsrRouteImport.update({
  id: '/asr',
  path: '/asr',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSlugRoute = TasksSlugRouteImport.update({
  id: '/tasks/$slug',
  path: '/tasks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asr': typeof AsrRoute
  '/audio-classification': typeof AudioClassificationRoute
  '/audio-to-audio': typeof AudioToAudioRoute
  '/depth': typeof DepthRoute
  '/home': typeof HomeRoute
  '/image-classification': typeof ImageClassificationRoute
  '/image-features': typeof ImageFeaturesRoute
  '/image-to-text': typeof ImageToTextRoute
  '/login': typeof LoginRoute
  '/mask-generation': typeof MaskGenerationRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/playground': typeof PlaygroundRoute
  '/pose': typeof PoseRoute
  '/segmentation': typeof SegmentationRoute
  '/signup': typeof SignupRoute
  '/tensor': typeof TensorRoute
  '/text-to-audio': typeof TextToAudioRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/training': typeof TrainingRoute
  '/vad': typeof VadRoute
  '/video-classification': typeof VideoClassificationRoute
  '/zero-shot-image-classification': typeof ZeroShotImageClassificationRoute
  '/zero-shot-object-detection': typeof ZeroShotObjectDetectionRoute
  '/tasks/$slug': typeof TasksSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asr': typeof AsrRoute
  '/audio-classification': typeof AudioClassificationRoute
  '/audio-to-audio': typeof AudioToAudioRoute
  '/depth': typeof DepthRoute
  '/home': typeof HomeRoute
  '/image-classification': typeof ImageClassificationRoute
  '/image-features': typeof ImageFeaturesRoute
  '/image-to-text': typeof ImageToTextRoute
  '/login': typeof LoginRoute
  '/mask-generation': typeof MaskGenerationRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/playground': typeof PlaygroundRoute
  '/pose': typeof PoseRoute
  '/segmentation': typeof SegmentationRoute
  '/signup': typeof SignupRoute
  '/tensor': typeof TensorRoute
  '/text-to-audio': typeof TextToAudioRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/training': typeof TrainingRoute
  '/vad': typeof VadRoute
  '/video-classification': typeof VideoClassificationRoute
  '/zero-shot-image-classification': typeof ZeroShotImageClassificationRoute
  '/zero-shot-object-detection': typeof ZeroShotObjectDetectionRoute
  '/tasks/$slug': typeof TasksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asr': typeof AsrRoute
  '/audio-classification': typeof AudioClassificationRoute
  '/audio-to-audio': typeof AudioToAudioRoute
  '/depth': typeof DepthRoute
  '/home': typeof HomeRoute
  '/image-classification': typeof ImageClassificationRoute
  '/image-features': typeof ImageFeaturesRoute
  '/image-to-text': typeof ImageToTextRoute
  '/login': typeof LoginRoute
  '/mask-generation': typeof MaskGenerationRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/playground': typeof PlaygroundRoute
  '/pose': typeof PoseRoute
  '/segmentation': typeof SegmentationRoute
  '/signup': typeof SignupRoute
  '/tensor': typeof TensorRoute
  '/text-to-audio': typeof TextToAudioRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/training': typeof TrainingRoute
  '/vad': typeof VadRoute
  '/video-classification': typeof VideoClassificationRoute
  '/zero-shot-image-classification': typeof ZeroShotImageClassificationRoute
  '/zero-shot-object-detection': typeof ZeroShotObjectDetectionRoute
  '/tasks/$slug': typeof TasksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asr'
    | '/audio-classification'
    | '/audio-to-audio'
    | '/depth'
    | '/home'
    | '/image-classification'
    | '/image-features'
    | '/image-to-text'
    | '/login'
    | '/mask-generation'
    | '/object-detection'
    | '/playground'
    | '/pose'
    | '/segmentation'
    | '/signup'
    | '/tensor'
    | '/text-to-audio'
    | '/text-to-speech'
    | '/training'
    | '/vad'
    | '/video-classification'
    | '/zero-shot-image-classification'
    | '/zero-shot-object-detection'
    | '/tasks/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asr'
    | '/audio-classification'
    | '/audio-to-audio'
    | '/depth'
    | '/home'
    | '/image-classification'
    | '/image-features'
    | '/image-to-text'
    | '/login'
    | '/mask-generation'
    | '/object-detection'
    | '/playground'
    | '/pose'
    | '/segmentation'
    | '/signup'
    | '/tensor'
    | '/text-to-audio'
    | '/text-to-speech'
    | '/training'
    | '/vad'
    | '/video-classification'
    | '/zero-shot-image-classification'
    | '/zero-shot-object-detection'
    | '/tasks/$slug'
  id:
    | '__root__'
    | '/'
    | '/asr'
    | '/audio-classification'
    | '/audio-to-audio'
    | '/depth'
    | '/home'
    | '/image-classification'
    | '/image-features'
    | '/image-to-text'
    | '/login'
    | '/mask-generation'
    | '/object-detection'
    | '/playground'
    | '/pose'
    | '/segmentation'
    | '/signup'
    | '/tensor'
    | '/text-to-audio'
    | '/text-to-speech'
    | '/training'
    | '/vad'
    | '/video-classification'
    | '/zero-shot-image-classification'
    | '/zero-shot-object-detection'
    | '/tasks/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsrRoute: typeof AsrRoute
  AudioClassificationRoute: typeof AudioClassificationRoute
  AudioToAudioRoute: typeof AudioToAudioRoute
  DepthRoute: typeof DepthRoute
  HomeRoute: typeof HomeRoute
  ImageClassificationRoute: typeof ImageClassificationRoute
  ImageFeaturesRoute: typeof ImageFeaturesRoute
  ImageToTextRoute: typeof ImageToTextRoute
  LoginRoute: typeof LoginRoute
  MaskGenerationRoute: typeof MaskGenerationRoute
  ObjectDetectionRoute: typeof ObjectDetectionRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PoseRoute: typeof PoseRoute
  SegmentationRoute: typeof SegmentationRoute
  SignupRoute: typeof SignupRoute
  TensorRoute: typeof TensorRoute
  TextToAudioRoute: typeof TextToAudioRoute
  TextToSpeechRoute: typeof TextToSpeechRoute
  TrainingRoute: typeof TrainingRoute
  VadRoute: typeof VadRoute
  VideoClassificationRoute: typeof VideoClassificationRoute
  ZeroShotImageClassificationRoute: typeof ZeroShotImageClassificationRoute
  ZeroShotObjectDetectionRoute: typeof ZeroShotObjectDetectionRoute
  TasksSlugRoute: typeof TasksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zero-shot-object-detection': {
      id: '/zero-shot-object-detection'
      path: '/zero-shot-object-detection'
      fullPath: '/zero-shot-object-detection'
      preLoaderRoute: typeof ZeroShotObjectDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zero-shot-image-classification': {
      id: '/zero-shot-image-classification'
      path: '/zero-shot-image-classification'
      fullPath: '/zero-shot-image-classification'
      preLoaderRoute: typeof ZeroShotImageClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-classification': {
      id: '/video-classification'
      path: '/video-classification'
      fullPath: '/video-classification'
      preLoaderRoute: typeof VideoClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vad': {
      id: '/vad'
      path: '/vad'
      fullPath: '/vad'
      preLoaderRoute: typeof VadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-to-speech': {
      id: '/text-to-speech'
      path: '/text-to-speech'
      fullPath: '/text-to-speech'
      preLoaderRoute: typeof TextToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-to-audio': {
      id: '/text-to-audio'
      path: '/text-to-audio'
      fullPath: '/text-to-audio'
      preLoaderRoute: typeof TextToAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tensor': {
      id: '/tensor'
      path: '/tensor'
      fullPath: '/tensor'
      preLoaderRoute: typeof TensorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentation': {
      id: '/segmentation'
      path: '/segmentation'
      fullPath: '/segmentation'
      preLoaderRoute: typeof SegmentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pose': {
      id: '/pose'
      path: '/pose'
      fullPath: '/pose'
      preLoaderRoute: typeof PoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object-detection': {
      id: '/object-detection'
      path: '/object-detection'
      fullPath: '/object-detection'
      preLoaderRoute: typeof ObjectDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mask-generation': {
      id: '/mask-generation'
      path: '/mask-generation'
      fullPath: '/mask-generation'
      preLoaderRoute: typeof MaskGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-text': {
      id: '/image-to-text'
      path: '/image-to-text'
      fullPath: '/image-to-text'
      preLoaderRoute: typeof ImageToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-features': {
      id: '/image-features'
      path: '/image-features'
      fullPath: '/image-features'
      preLoaderRoute: typeof ImageFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-classification': {
      id: '/image-classification'
      path: '/image-classification'
      fullPath: '/image-classification'
      preLoaderRoute: typeof ImageClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depth': {
      id: '/depth'
      path: '/depth'
      fullPath: '/depth'
      preLoaderRoute: typeof DepthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-to-audio': {
      id: '/audio-to-audio'
      path: '/audio-to-audio'
      fullPath: '/audio-to-audio'
      preLoaderRoute: typeof AudioToAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-classification': {
      id: '/audio-classification'
      path: '/audio-classification'
      fullPath: '/audio-classification'
      preLoaderRoute: typeof AudioClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asr': {
      id: '/asr'
      path: '/asr'
      fullPath: '/asr'
      preLoaderRoute: typeof AsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$slug': {
      id: '/tasks/$slug'
      path: '/tasks/$slug'
      fullPath: '/tasks/$slug'
      preLoaderRoute: typeof TasksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsrRoute: AsrRoute,
  AudioClassificationRoute: AudioClassificationRoute,
  AudioToAudioRoute: AudioToAudioRoute,
  DepthRoute: DepthRoute,
  HomeRoute: HomeRoute,
  ImageClassificationRoute: ImageClassificationRoute,
  ImageFeaturesRoute: ImageFeaturesRoute,
  ImageToTextRoute: ImageToTextRoute,
  LoginRoute: LoginRoute,
  MaskGenerationRoute: MaskGenerationRoute,
  ObjectDetectionRoute: ObjectDetectionRoute,
  PlaygroundRoute: PlaygroundRoute,
  PoseRoute: PoseRoute,
  SegmentationRoute: SegmentationRoute,
  SignupRoute: SignupRoute,
  TensorRoute: TensorRoute,
  TextToAudioRoute: TextToAudioRoute,
  TextToSpeechRoute: TextToSpeechRoute,
  TrainingRoute: TrainingRoute,
  VadRoute: VadRoute,
  VideoClassificationRoute: VideoClassificationRoute,
  ZeroShotImageClassificationRoute: ZeroShotImageClassificationRoute,
  ZeroShotObjectDetectionRoute: ZeroShotObjectDetectionRoute,
  TasksSlugRoute: TasksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
