/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeroShotObjectDetectionRouteImport } from './routes/zero-shot-object-detection'
import { Route as ZeroShotImageClassificationRouteImport } from './routes/zero-shot-image-classification'
import { Route as ZeroShotClassificationRouteImport } from './routes/zero-shot-classification'
import { Route as VisualQuestionAnsweringRouteImport } from './routes/visual-question-answering'
import { Route as VideoTextToTextRouteImport } from './routes/video-text-to-text'
import { Route as VideoClassificationRouteImport } from './routes/video-classification'
import { Route as VadRouteImport } from './routes/vad'
import { Route as TranslationRouteImport } from './routes/translation'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TokenClassificationRouteImport } from './routes/token-classification'
import { Route as TextToSpeechRouteImport } from './routes/text-to-speech'
import { Route as TextFeaturesRouteImport } from './routes/text-features'
import { Route as TextClassificationRouteImport } from './routes/text-classification'
import { Route as TensorRouteImport } from './routes/tensor'
import { Route as SuperResolutionRouteImport } from './routes/super-resolution'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SentenceSimilarityRouteImport } from './routes/sentence-similarity'
import { Route as SegmentationRouteImport } from './routes/segmentation'
import { Route as QuestionAnsweringRouteImport } from './routes/question-answering'
import { Route as PoseRouteImport } from './routes/pose'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ObjectDetectionRouteImport } from './routes/object-detection'
import { Route as MaskGenerationRouteImport } from './routes/mask-generation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkPredictionRouteImport } from './routes/link-prediction'
import { Route as ImageTo3dRouteImport } from './routes/image-to-3d'
import { Route as ImageTextToTextRouteImport } from './routes/image-text-to-text'
import { Route as ImageFeaturesRouteImport } from './routes/image-features'
import { Route as ImageClassificationRouteImport } from './routes/image-classification'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GraphClassificationRouteImport } from './routes/graph-classification'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as FillMaskRouteImport } from './routes/fill-mask'
import { Route as DepthRouteImport } from './routes/depth'
import { Route as BackgroundRemovalRouteImport } from './routes/background-removal'
import { Route as AudioToAudioRouteImport } from './routes/audio-to-audio'
import { Route as AudioClassificationRouteImport } from './routes/audio-classification'
import { Route as AsrRouteImport } from './routes/asr'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksSlugRouteImport } from './routes/tasks.$slug'

const ZeroShotObjectDetectionRoute = ZeroShotObjectDetectionRouteImport.update({
  id: '/zero-shot-object-detection',
  path: '/zero-shot-object-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeroShotImageClassificationRoute =
  ZeroShotImageClassificationRouteImport.update({
    id: '/zero-shot-image-classification',
    path: '/zero-shot-image-classification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ZeroShotClassificationRoute = ZeroShotClassificationRouteImport.update({
  id: '/zero-shot-classification',
  path: '/zero-shot-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualQuestionAnsweringRoute = VisualQuestionAnsweringRouteImport.update({
  id: '/visual-question-answering',
  path: '/visual-question-answering',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoTextToTextRoute = VideoTextToTextRouteImport.update({
  id: '/video-text-to-text',
  path: '/video-text-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoClassificationRoute = VideoClassificationRouteImport.update({
  id: '/video-classification',
  path: '/video-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const VadRoute = VadRouteImport.update({
  id: '/vad',
  path: '/vad',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslationRoute = TranslationRouteImport.update({
  id: '/translation',
  path: '/translation',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenClassificationRoute = TokenClassificationRouteImport.update({
  id: '/token-classification',
  path: '/token-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToSpeechRoute = TextToSpeechRouteImport.update({
  id: '/text-to-speech',
  path: '/text-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const TextFeaturesRoute = TextFeaturesRouteImport.update({
  id: '/text-features',
  path: '/text-features',
  getParentRoute: () => rootRouteImport,
} as any)
const TextClassificationRoute = TextClassificationRouteImport.update({
  id: '/text-classification',
  path: '/text-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const TensorRoute = TensorRouteImport.update({
  id: '/tensor',
  path: '/tensor',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperResolutionRoute = SuperResolutionRouteImport.update({
  id: '/super-resolution',
  path: '/super-resolution',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SentenceSimilarityRoute = SentenceSimilarityRouteImport.update({
  id: '/sentence-similarity',
  path: '/sentence-similarity',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentationRoute = SegmentationRouteImport.update({
  id: '/segmentation',
  path: '/segmentation',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionAnsweringRoute = QuestionAnsweringRouteImport.update({
  id: '/question-answering',
  path: '/question-answering',
  getParentRoute: () => rootRouteImport,
} as any)
const PoseRoute = PoseRouteImport.update({
  id: '/pose',
  path: '/pose',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectDetectionRoute = ObjectDetectionRouteImport.update({
  id: '/object-detection',
  path: '/object-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const MaskGenerationRoute = MaskGenerationRouteImport.update({
  id: '/mask-generation',
  path: '/mask-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkPredictionRoute = LinkPredictionRouteImport.update({
  id: '/link-prediction',
  path: '/link-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageTo3dRoute = ImageTo3dRouteImport.update({
  id: '/image-to-3d',
  path: '/image-to-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageTextToTextRoute = ImageTextToTextRouteImport.update({
  id: '/image-text-to-text',
  path: '/image-text-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageFeaturesRoute = ImageFeaturesRouteImport.update({
  id: '/image-features',
  path: '/image-features',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageClassificationRoute = ImageClassificationRouteImport.update({
  id: '/image-classification',
  path: '/image-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphClassificationRoute = GraphClassificationRouteImport.update({
  id: '/graph-classification',
  path: '/graph-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const FillMaskRoute = FillMaskRouteImport.update({
  id: '/fill-mask',
  path: '/fill-mask',
  getParentRoute: () => rootRouteImport,
} as any)
const DepthRoute = DepthRouteImport.update({
  id: '/depth',
  path: '/depth',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundRemovalRoute = BackgroundRemovalRouteImport.update({
  id: '/background-removal',
  path: '/background-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioToAudioRoute = AudioToAudioRouteImport.update({
  id: '/audio-to-audio',
  path: '/audio-to-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioClassificationRoute = AudioClassificationRouteImport.update({
  id: '/audio-classification',
  path: '/audio-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const AsrRoute = AsrRouteImport.update({
  id: '/asr',
  path: '/asr',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSlugRoute = TasksSlugRouteImport.update({
  id: '/tasks/$slug',
  path: '/tasks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asr': typeof AsrRoute
  '/audio-classification': typeof AudioClassificationRoute
  '/audio-to-audio': typeof AudioToAudioRoute
  '/background-removal': typeof BackgroundRemovalRoute
  '/depth': typeof DepthRoute
  '/fill-mask': typeof FillMaskRoute
  '/graph': typeof GraphRoute
  '/graph-classification': typeof GraphClassificationRoute
  '/home': typeof HomeRoute
  '/image-classification': typeof ImageClassificationRoute
  '/image-features': typeof ImageFeaturesRoute
  '/image-text-to-text': typeof ImageTextToTextRoute
  '/image-to-3d': typeof ImageTo3dRoute
  '/link-prediction': typeof LinkPredictionRoute
  '/login': typeof LoginRoute
  '/mask-generation': typeof MaskGenerationRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/playground': typeof PlaygroundRoute
  '/pose': typeof PoseRoute
  '/question-answering': typeof QuestionAnsweringRoute
  '/segmentation': typeof SegmentationRoute
  '/sentence-similarity': typeof SentenceSimilarityRoute
  '/signup': typeof SignupRoute
  '/super-resolution': typeof SuperResolutionRoute
  '/tensor': typeof TensorRoute
  '/text-classification': typeof TextClassificationRoute
  '/text-features': typeof TextFeaturesRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/token-classification': typeof TokenClassificationRoute
  '/training': typeof TrainingRoute
  '/translation': typeof TranslationRoute
  '/vad': typeof VadRoute
  '/video-classification': typeof VideoClassificationRoute
  '/video-text-to-text': typeof VideoTextToTextRoute
  '/visual-question-answering': typeof VisualQuestionAnsweringRoute
  '/zero-shot-classification': typeof ZeroShotClassificationRoute
  '/zero-shot-image-classification': typeof ZeroShotImageClassificationRoute
  '/zero-shot-object-detection': typeof ZeroShotObjectDetectionRoute
  '/tasks/$slug': typeof TasksSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asr': typeof AsrRoute
  '/audio-classification': typeof AudioClassificationRoute
  '/audio-to-audio': typeof AudioToAudioRoute
  '/background-removal': typeof BackgroundRemovalRoute
  '/depth': typeof DepthRoute
  '/fill-mask': typeof FillMaskRoute
  '/graph': typeof GraphRoute
  '/graph-classification': typeof GraphClassificationRoute
  '/home': typeof HomeRoute
  '/image-classification': typeof ImageClassificationRoute
  '/image-features': typeof ImageFeaturesRoute
  '/image-text-to-text': typeof ImageTextToTextRoute
  '/image-to-3d': typeof ImageTo3dRoute
  '/link-prediction': typeof LinkPredictionRoute
  '/login': typeof LoginRoute
  '/mask-generation': typeof MaskGenerationRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/playground': typeof PlaygroundRoute
  '/pose': typeof PoseRoute
  '/question-answering': typeof QuestionAnsweringRoute
  '/segmentation': typeof SegmentationRoute
  '/sentence-similarity': typeof SentenceSimilarityRoute
  '/signup': typeof SignupRoute
  '/super-resolution': typeof SuperResolutionRoute
  '/tensor': typeof TensorRoute
  '/text-classification': typeof TextClassificationRoute
  '/text-features': typeof TextFeaturesRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/token-classification': typeof TokenClassificationRoute
  '/training': typeof TrainingRoute
  '/translation': typeof TranslationRoute
  '/vad': typeof VadRoute
  '/video-classification': typeof VideoClassificationRoute
  '/video-text-to-text': typeof VideoTextToTextRoute
  '/visual-question-answering': typeof VisualQuestionAnsweringRoute
  '/zero-shot-classification': typeof ZeroShotClassificationRoute
  '/zero-shot-image-classification': typeof ZeroShotImageClassificationRoute
  '/zero-shot-object-detection': typeof ZeroShotObjectDetectionRoute
  '/tasks/$slug': typeof TasksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asr': typeof AsrRoute
  '/audio-classification': typeof AudioClassificationRoute
  '/audio-to-audio': typeof AudioToAudioRoute
  '/background-removal': typeof BackgroundRemovalRoute
  '/depth': typeof DepthRoute
  '/fill-mask': typeof FillMaskRoute
  '/graph': typeof GraphRoute
  '/graph-classification': typeof GraphClassificationRoute
  '/home': typeof HomeRoute
  '/image-classification': typeof ImageClassificationRoute
  '/image-features': typeof ImageFeaturesRoute
  '/image-text-to-text': typeof ImageTextToTextRoute
  '/image-to-3d': typeof ImageTo3dRoute
  '/link-prediction': typeof LinkPredictionRoute
  '/login': typeof LoginRoute
  '/mask-generation': typeof MaskGenerationRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/playground': typeof PlaygroundRoute
  '/pose': typeof PoseRoute
  '/question-answering': typeof QuestionAnsweringRoute
  '/segmentation': typeof SegmentationRoute
  '/sentence-similarity': typeof SentenceSimilarityRoute
  '/signup': typeof SignupRoute
  '/super-resolution': typeof SuperResolutionRoute
  '/tensor': typeof TensorRoute
  '/text-classification': typeof TextClassificationRoute
  '/text-features': typeof TextFeaturesRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/token-classification': typeof TokenClassificationRoute
  '/training': typeof TrainingRoute
  '/translation': typeof TranslationRoute
  '/vad': typeof VadRoute
  '/video-classification': typeof VideoClassificationRoute
  '/video-text-to-text': typeof VideoTextToTextRoute
  '/visual-question-answering': typeof VisualQuestionAnsweringRoute
  '/zero-shot-classification': typeof ZeroShotClassificationRoute
  '/zero-shot-image-classification': typeof ZeroShotImageClassificationRoute
  '/zero-shot-object-detection': typeof ZeroShotObjectDetectionRoute
  '/tasks/$slug': typeof TasksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asr'
    | '/audio-classification'
    | '/audio-to-audio'
    | '/background-removal'
    | '/depth'
    | '/fill-mask'
    | '/graph'
    | '/graph-classification'
    | '/home'
    | '/image-classification'
    | '/image-features'
    | '/image-text-to-text'
    | '/image-to-3d'
    | '/link-prediction'
    | '/login'
    | '/mask-generation'
    | '/object-detection'
    | '/playground'
    | '/pose'
    | '/question-answering'
    | '/segmentation'
    | '/sentence-similarity'
    | '/signup'
    | '/super-resolution'
    | '/tensor'
    | '/text-classification'
    | '/text-features'
    | '/text-to-speech'
    | '/token-classification'
    | '/training'
    | '/translation'
    | '/vad'
    | '/video-classification'
    | '/video-text-to-text'
    | '/visual-question-answering'
    | '/zero-shot-classification'
    | '/zero-shot-image-classification'
    | '/zero-shot-object-detection'
    | '/tasks/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asr'
    | '/audio-classification'
    | '/audio-to-audio'
    | '/background-removal'
    | '/depth'
    | '/fill-mask'
    | '/graph'
    | '/graph-classification'
    | '/home'
    | '/image-classification'
    | '/image-features'
    | '/image-text-to-text'
    | '/image-to-3d'
    | '/link-prediction'
    | '/login'
    | '/mask-generation'
    | '/object-detection'
    | '/playground'
    | '/pose'
    | '/question-answering'
    | '/segmentation'
    | '/sentence-similarity'
    | '/signup'
    | '/super-resolution'
    | '/tensor'
    | '/text-classification'
    | '/text-features'
    | '/text-to-speech'
    | '/token-classification'
    | '/training'
    | '/translation'
    | '/vad'
    | '/video-classification'
    | '/video-text-to-text'
    | '/visual-question-answering'
    | '/zero-shot-classification'
    | '/zero-shot-image-classification'
    | '/zero-shot-object-detection'
    | '/tasks/$slug'
  id:
    | '__root__'
    | '/'
    | '/asr'
    | '/audio-classification'
    | '/audio-to-audio'
    | '/background-removal'
    | '/depth'
    | '/fill-mask'
    | '/graph'
    | '/graph-classification'
    | '/home'
    | '/image-classification'
    | '/image-features'
    | '/image-text-to-text'
    | '/image-to-3d'
    | '/link-prediction'
    | '/login'
    | '/mask-generation'
    | '/object-detection'
    | '/playground'
    | '/pose'
    | '/question-answering'
    | '/segmentation'
    | '/sentence-similarity'
    | '/signup'
    | '/super-resolution'
    | '/tensor'
    | '/text-classification'
    | '/text-features'
    | '/text-to-speech'
    | '/token-classification'
    | '/training'
    | '/translation'
    | '/vad'
    | '/video-classification'
    | '/video-text-to-text'
    | '/visual-question-answering'
    | '/zero-shot-classification'
    | '/zero-shot-image-classification'
    | '/zero-shot-object-detection'
    | '/tasks/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsrRoute: typeof AsrRoute
  AudioClassificationRoute: typeof AudioClassificationRoute
  AudioToAudioRoute: typeof AudioToAudioRoute
  BackgroundRemovalRoute: typeof BackgroundRemovalRoute
  DepthRoute: typeof DepthRoute
  FillMaskRoute: typeof FillMaskRoute
  GraphRoute: typeof GraphRoute
  GraphClassificationRoute: typeof GraphClassificationRoute
  HomeRoute: typeof HomeRoute
  ImageClassificationRoute: typeof ImageClassificationRoute
  ImageFeaturesRoute: typeof ImageFeaturesRoute
  ImageTextToTextRoute: typeof ImageTextToTextRoute
  ImageTo3dRoute: typeof ImageTo3dRoute
  LinkPredictionRoute: typeof LinkPredictionRoute
  LoginRoute: typeof LoginRoute
  MaskGenerationRoute: typeof MaskGenerationRoute
  ObjectDetectionRoute: typeof ObjectDetectionRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PoseRoute: typeof PoseRoute
  QuestionAnsweringRoute: typeof QuestionAnsweringRoute
  SegmentationRoute: typeof SegmentationRoute
  SentenceSimilarityRoute: typeof SentenceSimilarityRoute
  SignupRoute: typeof SignupRoute
  SuperResolutionRoute: typeof SuperResolutionRoute
  TensorRoute: typeof TensorRoute
  TextClassificationRoute: typeof TextClassificationRoute
  TextFeaturesRoute: typeof TextFeaturesRoute
  TextToSpeechRoute: typeof TextToSpeechRoute
  TokenClassificationRoute: typeof TokenClassificationRoute
  TrainingRoute: typeof TrainingRoute
  TranslationRoute: typeof TranslationRoute
  VadRoute: typeof VadRoute
  VideoClassificationRoute: typeof VideoClassificationRoute
  VideoTextToTextRoute: typeof VideoTextToTextRoute
  VisualQuestionAnsweringRoute: typeof VisualQuestionAnsweringRoute
  ZeroShotClassificationRoute: typeof ZeroShotClassificationRoute
  ZeroShotImageClassificationRoute: typeof ZeroShotImageClassificationRoute
  ZeroShotObjectDetectionRoute: typeof ZeroShotObjectDetectionRoute
  TasksSlugRoute: typeof TasksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zero-shot-object-detection': {
      id: '/zero-shot-object-detection'
      path: '/zero-shot-object-detection'
      fullPath: '/zero-shot-object-detection'
      preLoaderRoute: typeof ZeroShotObjectDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zero-shot-image-classification': {
      id: '/zero-shot-image-classification'
      path: '/zero-shot-image-classification'
      fullPath: '/zero-shot-image-classification'
      preLoaderRoute: typeof ZeroShotImageClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zero-shot-classification': {
      id: '/zero-shot-classification'
      path: '/zero-shot-classification'
      fullPath: '/zero-shot-classification'
      preLoaderRoute: typeof ZeroShotClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-question-answering': {
      id: '/visual-question-answering'
      path: '/visual-question-answering'
      fullPath: '/visual-question-answering'
      preLoaderRoute: typeof VisualQuestionAnsweringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-text-to-text': {
      id: '/video-text-to-text'
      path: '/video-text-to-text'
      fullPath: '/video-text-to-text'
      preLoaderRoute: typeof VideoTextToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-classification': {
      id: '/video-classification'
      path: '/video-classification'
      fullPath: '/video-classification'
      preLoaderRoute: typeof VideoClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vad': {
      id: '/vad'
      path: '/vad'
      fullPath: '/vad'
      preLoaderRoute: typeof VadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translation': {
      id: '/translation'
      path: '/translation'
      fullPath: '/translation'
      preLoaderRoute: typeof TranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token-classification': {
      id: '/token-classification'
      path: '/token-classification'
      fullPath: '/token-classification'
      preLoaderRoute: typeof TokenClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-to-speech': {
      id: '/text-to-speech'
      path: '/text-to-speech'
      fullPath: '/text-to-speech'
      preLoaderRoute: typeof TextToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-features': {
      id: '/text-features'
      path: '/text-features'
      fullPath: '/text-features'
      preLoaderRoute: typeof TextFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-classification': {
      id: '/text-classification'
      path: '/text-classification'
      fullPath: '/text-classification'
      preLoaderRoute: typeof TextClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tensor': {
      id: '/tensor'
      path: '/tensor'
      fullPath: '/tensor'
      preLoaderRoute: typeof TensorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-resolution': {
      id: '/super-resolution'
      path: '/super-resolution'
      fullPath: '/super-resolution'
      preLoaderRoute: typeof SuperResolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentence-similarity': {
      id: '/sentence-similarity'
      path: '/sentence-similarity'
      fullPath: '/sentence-similarity'
      preLoaderRoute: typeof SentenceSimilarityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentation': {
      id: '/segmentation'
      path: '/segmentation'
      fullPath: '/segmentation'
      preLoaderRoute: typeof SegmentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-answering': {
      id: '/question-answering'
      path: '/question-answering'
      fullPath: '/question-answering'
      preLoaderRoute: typeof QuestionAnsweringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pose': {
      id: '/pose'
      path: '/pose'
      fullPath: '/pose'
      preLoaderRoute: typeof PoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object-detection': {
      id: '/object-detection'
      path: '/object-detection'
      fullPath: '/object-detection'
      preLoaderRoute: typeof ObjectDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mask-generation': {
      id: '/mask-generation'
      path: '/mask-generation'
      fullPath: '/mask-generation'
      preLoaderRoute: typeof MaskGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-prediction': {
      id: '/link-prediction'
      path: '/link-prediction'
      fullPath: '/link-prediction'
      preLoaderRoute: typeof LinkPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-3d': {
      id: '/image-to-3d'
      path: '/image-to-3d'
      fullPath: '/image-to-3d'
      preLoaderRoute: typeof ImageTo3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-text-to-text': {
      id: '/image-text-to-text'
      path: '/image-text-to-text'
      fullPath: '/image-text-to-text'
      preLoaderRoute: typeof ImageTextToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-features': {
      id: '/image-features'
      path: '/image-features'
      fullPath: '/image-features'
      preLoaderRoute: typeof ImageFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-classification': {
      id: '/image-classification'
      path: '/image-classification'
      fullPath: '/image-classification'
      preLoaderRoute: typeof ImageClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph-classification': {
      id: '/graph-classification'
      path: '/graph-classification'
      fullPath: '/graph-classification'
      preLoaderRoute: typeof GraphClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-mask': {
      id: '/fill-mask'
      path: '/fill-mask'
      fullPath: '/fill-mask'
      preLoaderRoute: typeof FillMaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depth': {
      id: '/depth'
      path: '/depth'
      fullPath: '/depth'
      preLoaderRoute: typeof DepthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-removal': {
      id: '/background-removal'
      path: '/background-removal'
      fullPath: '/background-removal'
      preLoaderRoute: typeof BackgroundRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-to-audio': {
      id: '/audio-to-audio'
      path: '/audio-to-audio'
      fullPath: '/audio-to-audio'
      preLoaderRoute: typeof AudioToAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-classification': {
      id: '/audio-classification'
      path: '/audio-classification'
      fullPath: '/audio-classification'
      preLoaderRoute: typeof AudioClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asr': {
      id: '/asr'
      path: '/asr'
      fullPath: '/asr'
      preLoaderRoute: typeof AsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$slug': {
      id: '/tasks/$slug'
      path: '/tasks/$slug'
      fullPath: '/tasks/$slug'
      preLoaderRoute: typeof TasksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsrRoute: AsrRoute,
  AudioClassificationRoute: AudioClassificationRoute,
  AudioToAudioRoute: AudioToAudioRoute,
  BackgroundRemovalRoute: BackgroundRemovalRoute,
  DepthRoute: DepthRoute,
  FillMaskRoute: FillMaskRoute,
  GraphRoute: GraphRoute,
  GraphClassificationRoute: GraphClassificationRoute,
  HomeRoute: HomeRoute,
  ImageClassificationRoute: ImageClassificationRoute,
  ImageFeaturesRoute: ImageFeaturesRoute,
  ImageTextToTextRoute: ImageTextToTextRoute,
  ImageTo3dRoute: ImageTo3dRoute,
  LinkPredictionRoute: LinkPredictionRoute,
  LoginRoute: LoginRoute,
  MaskGenerationRoute: MaskGenerationRoute,
  ObjectDetectionRoute: ObjectDetectionRoute,
  PlaygroundRoute: PlaygroundRoute,
  PoseRoute: PoseRoute,
  QuestionAnsweringRoute: QuestionAnsweringRoute,
  SegmentationRoute: SegmentationRoute,
  SentenceSimilarityRoute: SentenceSimilarityRoute,
  SignupRoute: SignupRoute,
  SuperResolutionRoute: SuperResolutionRoute,
  TensorRoute: TensorRoute,
  TextClassificationRoute: TextClassificationRoute,
  TextFeaturesRoute: TextFeaturesRoute,
  TextToSpeechRoute: TextToSpeechRoute,
  TokenClassificationRoute: TokenClassificationRoute,
  TrainingRoute: TrainingRoute,
  TranslationRoute: TranslationRoute,
  VadRoute: VadRoute,
  VideoClassificationRoute: VideoClassificationRoute,
  VideoTextToTextRoute: VideoTextToTextRoute,
  VisualQuestionAnsweringRoute: VisualQuestionAnsweringRoute,
  ZeroShotClassificationRoute: ZeroShotClassificationRoute,
  ZeroShotImageClassificationRoute: ZeroShotImageClassificationRoute,
  ZeroShotObjectDetectionRoute: ZeroShotObjectDetectionRoute,
  TasksSlugRoute: TasksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
